Added ability to install one or more DTR replicas
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

diff --git a/scripts/dind_ddc b/scripts/dind_ddc
--- a/scripts/dind_ddc
+++ b/scripts/dind_ddc
@@ -87,6 +87,12 @@ validate_dtr_replicas() {
     echo "Error: The number of DTR_REPLICAS (${DTR_REPLICAS}) is less than 1; you will not be able to install DTR"
     exit 1
   fi
+
+  if ((DTR_REPLICAS>WORKERS))
+  then
+    echo "Error: The number of DTR_REPLICAS (${DTR_REPLICAS}) is greater then the number of UCP workers (${WORKERS}); you will not be able to install DTR with the specified number of replicas"
+    exit 1
+  fi
 }
 
 env_info() {
@@ -522,7 +528,7 @@ init_swarm() {
   # join managers
   for ((ENGINE_NUM=2; ENGINE_NUM<=MANAGERS; ENGINE_NUM++))
   do
-    echo "Joining docker${ENGINE_NUM} to the Swarm..."
+    echo "Joining ${PROJECT}_docker${ENGINE_NUM} to the Swarm..."
     #shellcheck disable=SC2086
     docker -H tcp://127.0.0.1:100${ENGINE_NUM} ${MANAGER_JOIN_COMMAND}
     echo -e "done.\n"
@@ -531,7 +537,7 @@ init_swarm() {
   # join workers
   for ((ENGINE_NUM=((MANAGERS+1)); ENGINE_NUM<=((MANAGERS+WORKERS)); ENGINE_NUM++))
   do
-    echo "Joining docker${ENGINE_NUM} to the Swarm..."
+    echo "Joining ${PROJECT}_docker${ENGINE_NUM} to the Swarm..."
     #shellcheck disable=SC2086
     docker -H tcp://127.0.0.1:100${ENGINE_NUM} ${WORKER_JOIN_COMMAND}
     echo -e "done.\n"
@@ -641,14 +647,30 @@ install_dtr() {
   # count the number of existing containers
   get_current_num_engines
 
-  DTR_NODE=$((MANAGERS+1))
-  echo "Loading DTR images on ${PROJECT}_docker${DTR_NODE}..."
-  docker -H tcp://127.0.0.1:100${DTR_NODE} load -i "${DTR_IMAGES}"
+
+  # load images and install dtr to first replica
+  ENGINE_NUM=$((MANAGERS+1))
+  echo "Loading DTR images on ${PROJECT}_docker${ENGINE_NUM}..."
+  docker -H tcp://127.0.0.1:100${ENGINE_NUM} load -i "${DTR_IMAGES}"
   echo -e "done.\n"
 
-  echo "Installing DTR on ${PROJECT}_docker${DTR_NODE}..."
+  echo "Installing DTR on ${PROJECT}_docker${ENGINE_NUM}..."
   #shellcheck disable=SC2086
-  docker -H tcp://127.0.0.1:100${DTR_NODE} run -it --rm "${DTR_REPO}":"${DTR_VERSION}" install ${DTR_OPTIONS} --ucp-url https://"${ALIAS_IP}:4443" --ucp-username admin --ucp-password docker123 --ucp-node "${PROJECT}"_docker${DTR_NODE} --ucp-ca "$(curl -ks https://"${ALIAS_IP}":4443/ca)" --dtr-external-url "${ALIAS_IP}" --dtr-storage-volume /data
+  docker -H tcp://127.0.0.1:100${ENGINE_NUM} run -it --rm "${DTR_REPO}":"${DTR_VERSION}" install ${DTR_OPTIONS} --ucp-url https://"${ALIAS_IP}:4443" --ucp-username admin --ucp-password docker123 --ucp-node "${PROJECT}"_docker${ENGINE_NUM} --ucp-ca "$(curl -ks https://"${ALIAS_IP}":4443/ca)" --dtr-external-url "${ALIAS_IP}" --dtr-storage-volume /data --replica-id 0000000000e${ENGINE_NUM}
+  echo -e "done.\n"
+
+  # load images and join additional DTR replicas
+  for ((ENGINE_NUM=((MANAGERS+2)); ENGINE_NUM<=((MANAGERS+DTR_REPLICAS)); ENGINE_NUM++))
+  do
+    echo "Loading DTR images on ${PROJECT}_docker${ENGINE_NUM}..."
+    docker -H tcp://127.0.0.1:100${ENGINE_NUM} load -i "${DTR_IMAGES}"
+    echo -e "done.\n"
+0
+    echo "Joining ${PROJECT}_docker${ENGINE_NUM} as a DTR replica..."
+    #shellcheck disable=SC2086
+    docker -H tcp://127.0.0.1:100${ENGINE_NUM} run -it --rm "${DTR_REPO}":"${DTR_VERSION}" join ${DTR_OPTIONS} --ucp-url https://"${ALIAS_IP}:4443" --ucp-username admin --ucp-password docker123 --ucp-node "${PROJECT}"_docker${ENGINE_NUM} --ucp-ca "$(curl -ks https://"${ALIAS_IP}":4443/ca)" --existing-replica-id 0000000000e$((MANAGERS+1)) --replica-id 0000000000e${ENGINE_NUM}
+    echo -e "done.\n"
+  done
 
   echo -e "\nDTR should now be available at https://${ALIAS_IP}/"
   echo -e "  Username: admin\tPassword: docker123"
