Changed to number validation
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

diff --git a/scripts/dind_ddc b/scripts/dind_ddc
--- a/scripts/dind_ddc
+++ b/scripts/dind_ddc
@@ -658,18 +658,19 @@ get_current_num_engines() {
   WORKERS="$(docker -H unix:///var/run/docker.sock ps -a --filter label=project="${PROJECT}" --filter label=role=worker --filter name=docker --format '{{.Names}}' | wc -l | tr -d ' ')"
 
   # validate the results we received
-  if ((MANAGERS<1))
-  then
-    echo "Error: The number of MANAGERS (${MANAGERS}) returned was not greater than 0"
-    exit 1
-  fi
+  case ${MANAGERS} in
+    ''|*[!0-9]*)
+      echo "Error: The number of MANAGERS (${MANAGERS}) returned was not a number"
+      exit 1
+      ;;
+  esac
 
-  # check for valid number of workers
-  if ((WORKERS<0))
-  then
-    echo "Warning: The number of WORKERS (${WORKERS}) returned was not greater than 0"
-    exit 1
-  fi
+  case ${WORKERS} in
+    ''|*[!0-9]*)
+      echo "Error: The number of WORKERS (${WORKERS}) returned was not a number"
+      exit 1
+      ;;
+  esac
 }
 
 init_swarm() {
